### ISSUE TITLE
Unable to apply policies for transitions.

### ISSUE THREAD

**Issue by Alexandertlt** [sebdesign/laravel-state-machine#47]
Hello!
I have some problems with use policies with state-machine.
I need the transition to occur only when the policy returns true.

Laravel 7.28.4
Installed "sebdesign/laravel-state-machine": "^3.1".
The config file config/state-machine.php is unchanged as in the documentation:
```
'callbacks' => [
	'guard' => [
		'guard_on_approving' => [
			'on' => 'approve',
			'can' => 'approve',
		],
	],
]
```
When I try to call apply('approve') I get an error: CallbackFactory::get needs the index "do" to be able to build a callback, array {"on":"approve","can":"approve"} given.

Please tell me what I'm doing wrong.

**Comment by sebdesign** [comment]
That's strange!

This condition should be true since there is a `can` key in the guard: https://github.com/sebdesign/laravel-state-machine/blob/master/src/Callback/ContainerAwareCallbackFactory.php#L45

Could you please copy/paste the whole stack trace of the error here?

**Comment by Alexandertlt** [comment]
Oh sure. Here he is:
```
SM\SMException: CallbackFactory::get needs the index "do" to be able to build a callback, array {"on":"approve","can":"approve"} given. in file C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\winzou\state-machine\src\SM\Callback\CallbackFactory.php on line 44

#0 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\winzou\state-machine\src\SM\StateMachine\StateMachine.php(214): SM\Callback\CallbackFactory->get(Array)
#1 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\winzou\state-machine\src\SM\StateMachine\StateMachine.php(99): SM\StateMachine\StateMachine->callCallbacks(Object(SM\Event\TransitionEvent), 'guard')
#2 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\winzou\state-machine\src\SM\StateMachine\StateMachine.php(107): SM\StateMachine\StateMachine->can('approve')
#3 C:\OSPanel\domains\ASTRAL\smtest\smtest\app\Http\Controllers\UserController.php(13): SM\StateMachine\StateMachine->apply('approve')
#4 [internal function]: App\Http\Controllers\UserController->index()
#5 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#6 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)
#7 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\UserController), 'index')
#8 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Route.php(196): Illuminate\Routing\Route->runController()
#9 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Router.php(685): Illuminate\Routing\Route->run()
#10 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#15 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#19 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Routing\Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#22 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\fruitcake\laravel-cors\src\HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 C:\OSPanel\domains\ASTRAL\smtest\smtest\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#37 C:\OSPanel\domains\ASTRAL\smtest\smtest\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#38 {main}
```

In User model was added method:

```
use SM\Factory\Factory as SMFactory;
....
public function sm()
{
	$factory = new SMFactory(config('state-machine'));

	return $factory->get($this, 'graphA');
}
```

**Comment by sebdesign** [comment]
Oh now I get it. You are using the wrong factory. The `SMFactory` is from `winzou/state-machine`, so it does not use the features of this package. Where did you find this example?

You should instantiate the factory/state machine with one following ways:

#### Get the factory from the interface
```php
use SM\Factory\FactoryInterface;

$factory = app(CallbackFactoryInterface::class);

return $factory->get($this, 'graphA');
```

#### Or get the factory from the alias
```php
$factory = app('sm.factory');

return $factory->get($this, 'graphA');
```

#### Or get the state machine directly from the facade
```php
use Sebdesign\SM\Facade as StateMachine;

return StateMachine::get($this, 'graphA');
```

**Comment by Alexandertlt** [comment]
Thank you very much Sébastien for your help!
Your option 2 worked for me.

I used the example from this article:
https://itnext.io/using-state-machines-in-laravel-bbc07384c232

**Comment by sebdesign** [comment]
Ah yes I remember this article, I'll notice the author to fix the example!

@jrmadsen67 could you take a look at this?

**Comment by jrmadsen67** [comment]
Thanks for catching - I'll take a look at this today

EDIT: I've updated to use the examples you provided above. Thanks again!
